//+======================================================================
// $Source: /users/chaize/newsvn/cvsroot/Calculation/AttributeComposer/src/AttributeComposerClass.java,v $
//
// Project:   	Tango Device Server
//
// Description:	java source code for the Ds_Composer class .
//              This class is a singleton class and implements everything
//              which exists only once for all the  Ds_Composer object
//              It inherits from the DeviceClass class.
//
// $Author: katyho $
//
// $Revision: 1.2 $
//
// $Log: not supported by cvs2svn $
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-======================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

package AttributeComposer;

import java.util.Vector;

import fr.esrf.Tango.DevFailed;
import fr.esrf.Tango.DispLevel;
import fr.esrf.TangoApi.DbDatum;
import fr.esrf.TangoDs.DeviceClass;
import fr.esrf.TangoDs.DeviceImpl;
import fr.esrf.TangoDs.SpectrumAttr;
import fr.esrf.TangoDs.TangoConst;
import fr.esrf.TangoDs.UserDefaultAttrProp;
import fr.esrf.TangoDs.Util;

public class AttributeComposerClass extends DeviceClass implements TangoConst
{
	/**
	 *	AttributeComposerClass class instance (it is a singleton).
	 */
	private static AttributeComposerClass	_instance = null;

	/**
	 *	Class properties array.
	 */
	private DbDatum[]	cl_prop = null;

	//--------- Start of properties data members ----------


//--------- End of properties data members ----------


//===================================================================			
//
// method : 		instance()
// 
// description : 	static method to retrieve the AttributeComposerClass object 
//					once it has been initialised
//
//===================================================================			
	public static AttributeComposerClass instance()
	{
		if (_instance == null)
		{
			System.err.println("AttributeComposerClass is not initialised !!!");
			System.err.println("Exiting");
			System.exit(-1);
		}
		return _instance;
	}

//===================================================================			
//
// method : 		Init()
// 
// description : 	static method to create/retrieve the AttributeComposerClass
//					object. This method is the only one which enables a 
//					user to create the object
//
// in :			- class_name : The class name
//
//===================================================================			
	public static AttributeComposerClass init(String class_name) throws DevFailed
	{
		if (_instance == null)
		{
			_instance = new AttributeComposerClass(class_name);
		}
		return _instance;
	}
	
//===================================================================			
//
// method : 		AttributeComposerClass()
// 
// description : 	constructor for the AttributeComposerClass class
//
// argument : in : 	- name : The class name
//
//===================================================================			
	protected AttributeComposerClass(String name) throws DevFailed
	{
		super(name);

		Util.out2.println("Entering AttributeComposerClass constructor");
		write_class_property();
		get_class_property();
	
		Util.out2.println("Leaving AttributeComposerClass constructor");
	}
	
//===================================================================			
//
// method : 		command_factory()
// 
// description : 	Create the command object(s) and store them in the
//					command list
//===================================================================			
	public void command_factory()
	{
		command_list.addElement(new ResetClass("Reset",
			Tango_DEV_VOID, Tango_DEV_VOID,
			"",
			"",
			DispLevel.OPERATOR));
		
		command_list.addElement(new GetAttributeNameForIndexClass("GetAttributeNameForIndex",
			Tango_DEV_SHORT, Tango_DEV_STRING,
			"The index of the spectrum data",
			"The attributeName corresponding to the argin index",
			DispLevel.OPERATOR));
		
		command_list.addElement(new GetTangoQualitiesClass("GetTangoQualities",
				Tango_DEV_VOID, Tango_DEVVAR_STRINGARRAY,
				"",
				"The list of the qualities",
				DispLevel.OPERATOR));
			
		command_list.addElement(new GetPriorityForQualityClass("GetPriorityForQuality",
				Tango_DEV_STRING, Tango_DEV_SHORT,
				"The qualities name (ex:VALID, ALARM)",
				"The priority of the quality",
				DispLevel.OPERATOR));

		//	add polling if any
		for (int i=0 ; i<command_list.size(); i++)
		{
			/*Command	cmd = (Command)*/command_list.elementAt(i);
		}
	}


//===================================================================			
//
// method : 		device_factory()
// 
// description : 	Create the device object(s) and store them in the 
//					device list
//
// argument : in : 	String[] devlist : The device name list
//
//===================================================================			
	public void device_factory(String[] devlist) throws DevFailed
	{
	
		for (int i=0 ; i<devlist.length ; i++)
		{
			Util.out4.println("Device name : " + devlist[i]);
						
			// Create device and add it into the device list
			//----------------------------------------------
			device_list.addElement(new AttributeComposer(this, devlist[i]));

			// Export device to the outside world
			//----------------------------------------------
			if (Util._UseDb == true)
				export_device(((DeviceImpl)(device_list.elementAt(i))));
			else
				export_device(((DeviceImpl)(device_list.elementAt(i))), devlist[i]);
		}
	}

//=============================================================================
//
//	Method:	attribute_factory(Vector att_list)
//
//=============================================================================
	public void attribute_factory(Vector att_list) throws DevFailed
	{
		//	Attribute : spectrumResult
		SpectrumAttr	spectrum_result = 
			new SpectrumAttr("spectrumResult", Tango_DEV_DOUBLE, 10000);
		UserDefaultAttrProp	spectrum_result_prop = new UserDefaultAttrProp();
		spectrum_result_prop.set_label("Spectrum Result");
		spectrum_result.set_default_properties(spectrum_result_prop);
		att_list.addElement(spectrum_result);
		
//		Attribute : runningAttributesList
		SpectrumAttr running_attribute_list = 
			new SpectrumAttr("runningAttributesList", Tango_DEV_STRING, 1000);
		UserDefaultAttrProp	running_attribute_list_prop = new UserDefaultAttrProp();
		running_attribute_list_prop.set_label("Running Attributes");
		running_attribute_list_prop.set_description("The list of the running attributes.");
		running_attribute_list.set_default_properties(running_attribute_list_prop);
		att_list.addElement(running_attribute_list);

		//	Attribute : unknownAttributesList
		SpectrumAttr	unknown_attribute_list = 
			new SpectrumAttr("unknownAttributesList", Tango_DEV_STRING, 1000);
		UserDefaultAttrProp	unknown_attribute_list_prop = new UserDefaultAttrProp();
		unknown_attribute_list_prop.set_label("Unknown Attributes");
		unknown_attribute_list_prop.set_description("The list of unknown attributes.");
		unknown_attribute_list.set_default_properties(unknown_attribute_list_prop);
		att_list.addElement(unknown_attribute_list);

		//	Attribute : attributesQualityList
		SpectrumAttr	attributes_state_list = 
			new SpectrumAttr("attributesQualityList", Tango_DEV_STRING, 1000);
		UserDefaultAttrProp	attributes_state_list_prop = new UserDefaultAttrProp();
		attributes_state_list_prop.set_label("Attributes Quality");
		attributes_state_list_prop.set_description("The list of the attribute quality in string format.\nCall GetAttributeNameForIndex to know which attribute corresponds to an index of the spectrum");
		attributes_state_list.set_default_properties(attributes_state_list_prop);
		att_list.addElement(attributes_state_list);

		//	Attribute : attributesNumberPriorityList
		SpectrumAttr	attributes_number_priority_list = 
			new SpectrumAttr("attributesNumberPriorityList", Tango_DEV_SHORT, 1000);
		UserDefaultAttrProp	attributes_number_priority_list_prop = new UserDefaultAttrProp();
		attributes_number_priority_list_prop.set_label("Attributes Priority");
		attributes_number_priority_list_prop.set_description("The list of the attributes quality in priority number format.\nCall GetAttributeNameForIndex to know which attributes corresponds to an index of the spectrum.\nCall GetPriorityForQuality to know the values of tango qualities.");
		attributes_number_priority_list.set_default_properties(attributes_number_priority_list_prop);
		att_list.addElement(attributes_number_priority_list);

	}

//===================================================================
/**
 *	Get the class property for specified name.
 *
 *	@param name The property name.
 */
//===================================================================
	public DbDatum get_class_property(String name)
	{
		for (int i=0 ; i<cl_prop.length ; i++)
			if (cl_prop[i].name.equals(name))
				return cl_prop[i];
		//	if not found, return  an empty DbDatum
		return new DbDatum(name);
	}

//===================================================================
/**
 *	Read the class properties from database.
 */
//===================================================================			
	public void get_class_property() throws DevFailed
	{
		//	Initialize your default values here.
		//------------------------------------------


		//	Read class properties from database.(Automatic code generation)
		//-------------------------------------------------------------
		if (Util._UseDb==false)
			return;
		String[]	propnames = {
			};

		//	Call database and extract values
		//--------------------------------------------
		cl_prop = get_db_class().get_property(propnames);
		//int	i = -1;

		//	End of Automatic code generation
		//-------------------------------------------------------------

	}

//===================================================================
/**
 *	Set class description as property in database
 */
//===================================================================			
	private void write_class_property() throws DevFailed
	{	
		//	First time, check if database used
		//--------------------------------------------
		if (Util._UseDb == false)
			return;

		//	Prepeare DbDatum
		//--------------------------------------------
		DbDatum[]	data = new DbDatum[2];
		data[0] = new DbDatum("ProjectTitle");
		data[0].insert("AttributeComposer");

		data[1] = new DbDatum("Description");
		data[1].insert("This device composed a spectrum attribute from a list of scalar attribute.");

		//	Call database and and values
		//--------------------------------------------
		get_db_class().put_property(data);
	}

}
