//+======================================================================
// $Source: /users/chaize/newsvn/cvsroot/Calculation/AttributeComposer/src/Ds_ComposerClass.java,v $
//
// Project:   	Tango Device Server
//
// Description:	java source code for the Ds_Composer class .
//              This class is a singleton class and implements everything
//              which exists only once for all the  Ds_Composer object
//              It inherits from the DeviceClass class.
//
// $Author: syldup $
//
// $Revision: 1.1.1.1 $
//
// $Log: not supported by cvs2svn $
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-======================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

package Ds_Composer;

import java.util.*;
import org.omg.CORBA.*;
import fr.esrf.Tango.*;
import fr.esrf.TangoDs.*;
import fr.esrf.TangoApi.*;

public class Ds_ComposerClass extends DeviceClass implements TangoConst
{
	/**
	 *	Ds_ComposerClass class instance (it is a singleton).
	 */
	private static Ds_ComposerClass	_instance = null;

	/**
	 *	Class properties array.
	 */
	private DbDatum[]	cl_prop = null;

	//--------- Start of properties data members ----------


//--------- End of properties data members ----------


//===================================================================			
//
// method : 		instance()
// 
// description : 	static method to retrieve the Ds_ComposerClass object 
//					once it has been initialised
//
//===================================================================			
	public static Ds_ComposerClass instance()
	{
		if (_instance == null)
		{
			System.err.println("Ds_ComposerClass is not initialised !!!");
			System.err.println("Exiting");
			System.exit(-1);
		}
		return _instance;
	}

//===================================================================			
//
// method : 		Init()
// 
// description : 	static method to create/retrieve the Ds_ComposerClass
//					object. This method is the only one which enables a 
//					user to create the object
//
// in :			- class_name : The class name
//
//===================================================================			
	public static Ds_ComposerClass init(String class_name) throws DevFailed
	{
		if (_instance == null)
		{
			_instance = new Ds_ComposerClass(class_name);
		}
		return _instance;
	}
	
//===================================================================			
//
// method : 		Ds_ComposerClass()
// 
// description : 	constructor for the Ds_ComposerClass class
//
// argument : in : 	- name : The class name
//
//===================================================================			
	protected Ds_ComposerClass(String name) throws DevFailed
	{
		super(name);

		Util.out2.println("Entering Ds_ComposerClass constructor");
		write_class_property();
		get_class_property();
	
		Util.out2.println("Leaving Ds_ComposerClass constructor");
	}
	
//===================================================================			
//
// method : 		command_factory()
// 
// description : 	Create the command object(s) and store them in the
//					command list
//===================================================================			
	public void command_factory()
	{
		command_list.addElement(new ResetClass("Reset",
			Tango_DEV_VOID, Tango_DEV_VOID,
			"",
			"",
			DispLevel.OPERATOR));
		command_list.addElement(new GetAttributeNameForIndexClass("GetAttributeNameForIndex",
			Tango_DEV_SHORT, Tango_DEV_STRING,
			"The index of the spectrum data",
			"The attributeName corresponding to the argin index",
			DispLevel.OPERATOR));

		//	add polling if any
		for (int i=0 ; i<command_list.size(); i++)
		{
			Command	cmd = (Command)command_list.elementAt(i);
		}
	}


//===================================================================			
//
// method : 		device_factory()
// 
// description : 	Create the device object(s) and store them in the 
//					device list
//
// argument : in : 	String[] devlist : The device name list
//
//===================================================================			
	public void device_factory(String[] devlist) throws DevFailed
	{
	
		for (int i=0 ; i<devlist.length ; i++)
		{
			Util.out4.println("Device name : " + devlist[i]);
						
			// Create device and add it into the device list
			//----------------------------------------------
			device_list.addElement(new Ds_Composer(this, devlist[i]));

			// Export device to the outside world
			//----------------------------------------------
			if (Util._UseDb == true)
				export_device(((DeviceImpl)(device_list.elementAt(i))));
			else
				export_device(((DeviceImpl)(device_list.elementAt(i))), devlist[i]);
		}
	}

//=============================================================================
//
//	Method:	attribute_factory(Vector att_list)
//
//=============================================================================
	public void attribute_factory(Vector att_list) throws DevFailed
	{
		//	Attribute : spectrumResult
		SpectrumAttr	spectrum_result = 
			new SpectrumAttr("spectrumResult", Tango_DEV_DOUBLE, 10000);
		UserDefaultAttrProp	spectrum_result_prop = new UserDefaultAttrProp();
		spectrum_result_prop.set_label("Spectrum Result");
		spectrum_result.set_default_properties(spectrum_result_prop);
		att_list.addElement(spectrum_result);

	}

//===================================================================
/**
 *	Get the class property for specified name.
 *
 *	@param name The property name.
 */
//===================================================================
	public DbDatum get_class_property(String name)
	{
		for (int i=0 ; i<cl_prop.length ; i++)
			if (cl_prop[i].name.equals(name))
				return cl_prop[i];
		//	if not found, return  an empty DbDatum
		return new DbDatum(name);
	}

//===================================================================
/**
 *	Read the class properties from database.
 */
//===================================================================			
	public void get_class_property() throws DevFailed
	{
		//	Initialize your default values here.
		//------------------------------------------


		//	Read class properties from database.(Automatic code generation)
		//-------------------------------------------------------------
		if (Util._UseDb==false)
			return;
		String[]	propnames = {
			};

		//	Call database and extract values
		//--------------------------------------------
		cl_prop = get_db_class().get_property(propnames);
		int	i = -1;

		//	End of Automatic code generation
		//-------------------------------------------------------------

	}

//===================================================================
/**
 *	Set class description as property in database
 */
//===================================================================			
	private void write_class_property() throws DevFailed
	{	
		//	First time, check if database used
		//--------------------------------------------
		if (Util._UseDb == false)
			return;

		//	Prepeare DbDatum
		//--------------------------------------------
		DbDatum[]	data = new DbDatum[2];
		data[0] = new DbDatum("ProjectTitle");
		data[0].insert("ds_Composer");

		data[1] = new DbDatum("Description");
		data[1].insert("This device composed a spectrum attribute from a list of scalar attribute.");

		//	Call database and and values
		//--------------------------------------------
		get_db_class().put_property(data);
	}

}
