//+======================================================================
// $Source: /users/chaize/newsvn/cvsroot/Calculation/AttributeComposer/src/SetPropertyClass.java,v $
//
// Project:      Tango Device Server
//
// Description:  Java source code for the command TemplateClass of the
//               AttributeComposer class.
//
// $Author: katyho $
//
// $Revision: 1.4 $
//
// $Log: not supported by cvs2svn $
// Revision 1.1  2006/04/25 15:02:49  katyho
// Update the documentation and Add new functions
//
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-======================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================



/**
 * @author	$Author: katyho $
 * @version	$Revision: 1.4 $
 */
package AttributeComposer;



import org.omg.CORBA.*;
import fr.esrf.Tango.*;
import fr.esrf.TangoDs.*;

/**
 *	Class Description:
 *	This command return the priority associated to a given State.
*/


public class SetPropertyClass extends Command implements TangoConst
{
	//===============================================================
	/**
	 *	Constructor for Command class GetPriorityForStateClass
	 *
	 *	@param	name	command name
	 *	@param	in	argin type
	 *	@param	out	argout type
	 */
	//===============================================================
	public SetPropertyClass(String name,int in,int out)
	{
		super(name, in, out);
	}

	//===============================================================
	/**
	 *	Constructor for Command class GetPriorityForStateClass
	 *
	 *	@param	name            command name
	 *	@param	in              argin type
	 *	@param	in_comments     argin description
	 *	@param	out             argout type
	 *	@param	out_comments    argout description
	 */
	//===============================================================
	public SetPropertyClass(String name,int in,int out, String in_comments, String out_comments)
	{
		super(name, in, out, in_comments, out_comments);
	}
	//===============================================================
	/**
	 *	Constructor for Command class GetPriorityForStateClass
	 *
	 *	@param	name            command name
	 *	@param	in              argin type
	 *	@param	in_comments     argin description
	 *	@param	out             argout type
	 *	@param	out_comments    argout description
	 *	@param	level           The command display type OPERATOR or EXPERT
	 */
	//===============================================================
	public SetPropertyClass(String name,int in,int out, String in_comments, String out_comments, DispLevel level)
	{
		super(name, in, out, in_comments, out_comments, level);
	}
	//===============================================================
	/**
	 *	return the result of the device's command.
	 */
	//===============================================================
	public Any execute(DeviceImpl device,Any in_any) throws DevFailed
	{
		Util.out2.println("SetProperty.execute(): arrived");
		if(name.equals("SetAllFormat"))
		{
		    String argin = extract_DevString(in_any);
		    ((AttributeComposer)(device)).set_all_format(argin);
		}
		if(name.equals("SetAllUnit"))
		{
		    String argin = extract_DevString(in_any);
		    ((AttributeComposer)(device)).set_all_unit(argin);
		}
		if(name.equals("SetAllMinValue"))
		{
		    double argin = extract_DevDouble(in_any);
		    ((AttributeComposer)(device)).set_all_min_value(argin);
		}
		if(name.equals("SetAllMaxValue"))
		{
		    double argin = extract_DevDouble(in_any);
		    ((AttributeComposer)(device)).set_all_max_value(argin);
		}
		if(name.equals("SetAllMinAlarm"))
		{
		    double argin = extract_DevDouble(in_any);
		    ((AttributeComposer)(device)).set_all_min_alarm(argin);
		} 
		if(name.equals("SetAllMaxAlarm"))
		{
		    double argin = extract_DevDouble(in_any);
		    ((AttributeComposer)(device)).set_all_max_alarm(argin);
		}
		if(name.equals("SetAllLabel"))
		{
		    String argin = extract_DevString(in_any);
		    ((AttributeComposer)(device)).set_all_label(argin);
		}
		
		return insert();
	}

	//===============================================================
	/**
	 *	Check if it is allowed to execute the command.
	 */
	//===============================================================
	public boolean is_allowed(DeviceImpl device, Any data_in)
	{
			//	End of Generated Code

			//	Re-Start of Generated Code
		return true;
	}
}
//-----------------------------------------------------------------------------
/* end of $Source: /users/chaize/newsvn/cvsroot/Calculation/AttributeComposer/src/SetPropertyClass.java,v $ */
